<a href="https://colab.research.google.com/github/james-monahan/Code-school-notebooks/blob/main/Week-5-python-sql/Numpy_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy : Introduction

**Numpy allows you to manipulate data in the form of an array.**

**Complete the missions below using Numpy.**

In [ ]:
# Mission 1 : Display the version of Numpy you are running
import numpy as np
np.__version__

'1.18.5'

In [ ]:
# Mission 2 : Create a Numpy array with a length of 3, that contains floats of the following format: 0.x, where x represents any value
#array1 = np.array([0.1, 0.2, 0.3])
array1 = np.random.rand(3)
array1.shape, array1

((3,), array([0.86679786, 0.53968498, 0.84676248]))

In [ ]:
# Mission 3 : Create a function that uses the random.random() method to display 10 random elements, all of which must be greater than 0.25
def np_rand_gen():
  return np.random.random(10)+.250001
np_rand_gen()

array([0.25174633, 0.90456173, 0.38299745, 0.36271486, 0.69074379,
       0.25584438, 1.06405838, 0.27471065, 0.58610395, 0.56815379])

In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here


#returns an array of the shape specified in a tuple. Array is filled with junk data, data type can be specified as an argument
# for large arrays it can be faster to produce as ir just grabs whatever
x = np.empty((3,3), dtype=int)
x

array([[59442032,        0,        0],
       [       0,        0,        0],
       [       0,        0,        0]])

In [ ]:
# Mission 5 : Create an array filled with floats that have 7 zeros.

zero_array = np.zeros((7,))
zero_array

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Mission 6 : Create an array filled with 10 random ints

rand_array = np.random.randint(0, 100, size=10)
rand_array

array([17,  9, 79,  7, 47, 32,  8, 88, 35, 40])

In [ ]:
# Mission 7 : Create an array that contains 70 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.

choice_array = np.random.choice([0, 1, 2, 3, 4, 5, 6, 7], size=70)
choice_array

array([5, 3, 7, 2, 2, 6, 7, 6, 5, 3, 6, 6, 0, 5, 0, 1, 0, 3, 0, 4, 3, 2,
       0, 5, 7, 1, 2, 2, 7, 4, 2, 4, 2, 4, 6, 5, 0, 2, 0, 7, 1, 2, 5, 3,
       3, 0, 6, 0, 5, 1, 2, 7, 2, 1, 7, 0, 3, 1, 1, 5, 6, 5, 3, 7, 2, 6,
       5, 7, 6, 5])

In [ ]:
# Mission 8 : Use the slicing operator to return the items between position 3 and 6 inclusive, from the array in mission 6

rand_array[3:7]

array([ 7, 47, 32,  8])

In [ ]:
# Mission 9 : Use a method to return the index of the smallest element in the array from mission 7

min = np.argmin(choice_array)
print('min value =', choice_array[min], 'min index = ', min)

min value = 0 min index =  12


In [ ]:
# Mission 10 : Using a numpy method, return the index of all the values in the array from mission 6 that are greater than their median value.

print(rand_array)
print(np.median(rand_array))
np.where(rand_array > np.median(rand_array))

[17  9 79  7 47 32  8 88 35 40]
33.5


(array([2, 4, 7, 8, 9]),)

In [ ]:
# Mission 11: Create 3 arrays filled with random ints, and place them in another array.
# Create a function that will go through the elements of the 3 arrays in turn.
# It should return: Element 1 of arrays 1, 2 and 3. Then element 2 of arrays 1, 2 and 3... etc.
arr1 = np.random.randint(0,10,(5,))
arr2 = np.random.randint(0,10,(5,))
arr3 = np.random.randint(0,10,(5,))
print(arr1, arr2, arr3)
print()
big_array = np.array([arr1, arr2, arr3])
print(big_array)
print()

def walk_array(np_array):
  for x in np.nditer(np_array, order='F'):
    print(x, end=' ')

walk_array(big_array)

[3 7 9 6 2] [9 7 7 5 8] [5 5 9 3 9]

[[3 7 9 6 2]
 [9 7 7 5 8]
 [5 5 9 3 9]]

3 9 5 7 7 5 9 7 9 6 5 3 2 8 9 

In [ ]:
# Mission 12: Create an array and fill it with 20 random float values.
# Create a function that will go through the array and return the smallest and largest value it contains.

rand_floats = np.random.random(size=20)
print(rand_floats)
print()

def array_sizes(sample_array):
  print(f'minimum = {np.min(sample_array)} maximum = {np.max(sample_array)}')

array_sizes(rand_floats)

[0.99281716 0.39482582 0.64814526 0.66266702 0.20573948 0.09007882
 0.7004145  0.11941671 0.28813144 0.38587878 0.26896739 0.46631888
 0.78859876 0.51370555 0.4334411  0.47538184 0.48672805 0.93644146
 0.07439425 0.74273583]

minimum = 0.0743942476023296 maximum = 0.9928171610799369


In [ ]:
# Mission 13: Create 2 arrays, randomly fill them with 20 int values between 0 and 10.
# Create a function that will go through each array using a while loop.
# At each iteration of the loop the function should compare the values of the 2 arrays located at the same index position.
# Return any index at which the values of the 2 arrays happen to be equal.
# If no values are equal at the same indices across the 2 arrays, return the message: "No values in common".

r_i_array1 = np.random.randint(0,11, size=20)
r_i_array2 = np.random.randint(0,11, size=20)

def compare_vals(array1, array2):
  counter = 0
  equals = []
  while counter < len(array1):
    if array1[counter] == array2[counter]:
      equals.append(counter)
      print(f'values match at index = {counter}')
    counter += 1
  if len(equals) == 0:
    print('No values in common')
  else:
    return equals
  print(array1) 
  print(array2)

compare_vals(r_i_array1, r_i_array2)

No values in common
[ 8  1  2  7  6  8  1  2  6  3  3 10  6  2  4  4  1  2  0  5]
[ 7  0  4  0  7  7  4  0  3  1  8  8  5  0  5  3  8  1 10  6]


In [ ]:
r_i_array1 = np.random.randint(1,11, size=20)
r_i_array2 = np.random.randint(1,11, size=20)
compare_vals(r_i_array1, r_i_array2)

values match at index = 4
values match at index = 17


[4, 17]